#include <stdio.h>
#include <signal.h>
#include <unistd.h>
#include <stdlib.h>

void alarm_handler(int signo){  ///function that's a place where alarams can be sent.
	if (signo == SIGALRM){     //SIGALRM is an asynchronous signal,it's raised when a time interval specified in a call to the alarm expires.
		printf("Alarm\n");
	}
	else if (signo == SIGINT){		//SIGINT is an interrupt from the keyboard
		printf("CTRL+C pressed!\n");
	}
	else if (signo == SIGTSTP){    //this is an interacitve stop signal that is usually generated by CTRL-Z. It can be handled or ignored.
		printf("CTRL+Z pressed!\n");
		exit(1);
	}
}

int main(void){
	if (signal(SIGALRM, alarm_handler) == SIG_ERR){   //signal makes the alarm_handler operational by registering with the kernel
		printf("failed to register alarm handler");
        exit(1);
	}
	if (signal(SIGINT, alarm_handler) == SIG_ERR){
		printf("failed to register alarm handler");
        exit(1);
	}
	if (signal(SIGTSTP, alarm_handler) == SIG_ERR){
		printf("failed to register alarm handler");
		exit(1);
	}

	
	while(1){
		alarm(2);    //generates a SIGALRM after a specified amount of seconds has elapsed.
		sleep(2); 	// sleeps until for the specified number of seconds or unitl a signal arrives which is not ignored.
	}
}
